### DISCUSSION TITLE
Accessing plate information in Automation

### DISCUSSION THREAD

**Discussion by michealc** [robmarkcole/HASS-plate-recognizer#61] [Q&A]
Hi, I apologise in advance if this is the wrong place as I am new to home assistant - 1 week.    I am running HA in a docker on my Synology NAS and using the stable version.  I have been able to add this extension to HA and I can trigger automation from either a state change or an event. 

The only issue I am having is adding the plate number into the notify message.  I have tried and copied a number of examples to obtain from the  image_processing object and the event object but I just get blanks.   I also note that with the image_processing object the vehicles attribute is an array and with the event it is just a plate attribute. 

Is there anything special that I am missing?  I have tried exhaustively to find a specific example where an event is triggering an automation script and data from the event is used as part of the message without any success.   Could you please point me to such a resource if one exists?

Regards
Micheal

**Comment by knighttv** [comment]
I have a trigger that fires when `platerecognizer.vehicle_detected` event is fired, and action is to call a notification service, here is the config....
```
service: notify.mobile_app_sm_s908b
data:
  title: "Plate: {{trigger.event.data.plate | upper}}"
  message: "Confidence: {{trigger.event.data.confidence}}"
```
Hope this helps
