### ISSUE TITLE
State issue

### ISSUE THREAD

**Issue by KillahB33** [robmarkcole/HASS-plate-recognizer#14]
Hey Robin, thanks again for pumping this out as fast as you did and making improvements as fast as you are.
I am running tests right now and for some reason one of my cameras is coming back wrong.
The current state is 1 even though the attributes look like the following.

```
last_detection: 2021-02-15_08-47-14
vehicles:
  - {}
statistics:
  total_calls: 2500
  usage:
    year: 2021
    month: 2
    resets_on: '2021-03-12T00:00:00Z'
    calls: 7
  calls_remaining: 2493
unit_of_measurement: plate
friendly_name: platerecognizer_front_left
```

Also here is my config if that helps.
```
# Platerecognizer site
image_processing:
  - platform: platerecognizer
    api_token: !secret
    region: 
      - ca
    save_file_folder: /config/images/plate_recognizer/
    save_timestamped_file: True
    source:
      - entity_id: camera.front_left
      - entity_id: camera.front_right
```

excuse all the revisions I accidently posted my api token
