### ISSUE TITLE
Empty pictures when using nest camera

### ISSUE THREAD

**Issue by henrikrox** [robmarkcole/HASS-plate-recognizer#52]
Hi

I’m using outdoor nest cameras that are 24/7 powered. I have setup the integration correctly but when start the image proccessing the png saved doesn’t  have a picture. The file is there in the confit folder but there is no picture, it’s just white 

I don’t have a car to test with this evening, does a car need to be in the frame of the camera for the image processing event to generate a picture?

**Comment by henrikrox** [comment]
```
image_processing:
  - platform: platerecognizer
    api_token: XXXXXXX
    regions:
      - no
    save_file_folder: /config/www/plates
    save_timestamped_file: True
    always_save_latest_file: True
    source:
      - entity_id: camera.kamera_garasje_hage
```

error in logs, don't know why it interprets Norway as false in region.
```
platerecognizer api response: {'regions': ['Region "False" does not exist. List of regions: http://docs.platerecognizer.com/#countries']}

platerecognizer error: 'results'
```
