### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by pilot1981** [robmarkcole/HASS-plate-recognizer#83]
Hi,
I would use this project to create an automation on HA to open my house’s gate when my car arrived in front!

I would use:
- free account https://app.platerecognizer.com/products/snapshot-cloud/ (2500 plate/month are sufficient because no many cars come in front of my house)
- check new cars in image every seconds

it’s possibile? You see any limitation?

I could have some issue with automation in this type of case?

**Comment by robmarkcole** [comment]
Should be fine, unless there are many false positives. You could just trigger on motion detection

**Comment by pilot1981** [comment]
I don't have webcam with motion detection: what you suggest to do? I can use some other software to process it and create a virtual motion detection? what's your suggestion?

**Comment by robmarkcole** [comment]
Hmm you could do some kind of routine based on geofencing. Simplest would be to install an actuall sensor on the gate, e.g. PIR

**Comment by pilot1981** [comment]
I can't use found event of image processing  of HA?

https://www.home-assistant.io/integrations/image_processing/


I create an automation that when event plate found is triggered...it send plate image to PlateRecognizer cloud...it can works?

**Comment by pilot1981** [comment]
Hi, I have proble creating 2 template sensors: 1 for each plate.

this is my configuration.yaml:
´´´
sensor:
  - platform: template
    sensors:
      plate_recognizer:
        friendly_name: "elxxxkf"
        value_template: "{{ state_attr('image_processing.platerecognizer_telecamera_retro3_2', 'watched_plates').elxxxkf }}"
  - platform: template
    sensors:
      plate_recognizer:
        friendly_name: "gfxxxky"
        value_template: "{{ state_attr('image_processing.platerecognizer_telecamera_retro3_2', 'watched_plates').gfxxxky }}"
´´´

but I only obtain elxxxkf sensor plate...no any gfxxxky sensor plate....why? you have some suggestion? I already tried the suggested config in your wiki...no luck!

**Comment by pilot1981** [comment]
hi @robmarkcole,
I see platerecognizer don't reset counter 20500 image processing every day: it have to reset it every day?

**Comment by pilot1981** [comment]
@robmarkcole you already tried to use API to obtain some data from platerecognizer cloud website to import in HA?

example:
- number of API calls of actual month
- image upload/process
- plate recognized
- plate not recognized
- ...

**Comment by pilot1981** [comment]
@robmarkcole ,
please update sensor template according to last version of HA; here my examples:

´´´
template:
  - sensor:
      - name: "targa_ELxxxKF"
        unique_id: plate_recognizer_elxxxkf
        state: "{{ state_attr('image_processing.platerecognizer_telecamera_cancello_profile_000', 'watched_plates').elxxxkf }}"
      - name: "targa_GFxxxKY"
        unique_id: plate_recognizer_gfxxxky 
        state: "{{ state_attr('image_processing.platerecognizer_telecamera_cancello_profile_000', 'watched_plates').gfxxxky }}"
´´´

**Comment by pilot1981** [comment]
Hi @robmarkcole,
using your custom components I found this error in my lgos:

`Logger: custom_components.platerecognizer.image_processing
Source: custom_components/platerecognizer/image_processing.py:210
Integration: platerecognizer (documentation)
First occurred: 10:34:25 (1 occurrences)
Last logged: 10:34:25

get_orientations error: 'orientation'`

what's it mean?

How I can solve it?

regards

**Comment by pilot1981** [comment]
according to https://www.home-assistant.io/integrations/image_processing/

why I don't found in my installation entity openlapr.xxxx?

it is possibile use built image processing feature of HA to send image to PlateRecognizer cloud only when a license plate is recognized?

**Comment by pilot1981** [comment]
Hi @robmarkcole,
I'm deployment an installation at home using your project, but I don't have license plate stay in front for camera foir many seconds soI'm not able to take and send the right image of license plate to platerecognizer cloud.

what do you suggest for it?

Car is under 20 km/h...when ONVIF camera send motion detection alarm, can I take and send 10 images to plate regcognizer cloud? do you suggest to use a custom automation for this purpose? do you have other suggestions?

regards

**Comment by robmarkcole** [comment]
So the problem is, since the car is moving, when motion triggers the e camera the car is already out of frame? In this case you need to process continually to detect the car with the camera, the send the best image to this integration. Checkout Frigate forums for an approach

**Comment by pilot1981** [comment]
for testing purpose, how I can uploda specific images to plate recognizer cloud?

**Comment by robmarkcole** [comment]
You can use the https://www.home-assistant.io/integrations/local_file/

**Comment by pilot1981** [comment]
Hi,
I'm trying to send to platerecognizer cloud multiple images to get the right image with the best license plate image, so I'm tryning to send 5 images in less than5 seconds, but I see only 2 images on plate recognizer cloud: there is some limitation in plate recognizer service?

I let also an example of HA automation I'm using:

```
alias: Test manda targa ripetuto 5 volte
description: Manda RIPETI 5 volte in automatico targa a platerecognizer
trigger:
  - platform: state
    entity_id:
      - binary_sensor.telecamera_cancello_cell_motion_detection
    from: null
    to: "on"
condition: []
action:
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_telecamera_cancello_profile_000
  - delay: "00:00:01"
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_telecamera_cancello_profile_000
  - delay: "00:00:01"
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_telecamera_cancello_profile_000
  - delay: "00:00:01"
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_telecamera_cancello_profile_000
  - delay: "00:00:01"
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_telecamera_cancello_profile_000
  - delay: "00:00:01"
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_telecamera_cancello_profile_000
  - delay: "00:00:01"
  - service: image_processing.scan
    data: {}
    target:
      entity_id: image_processing.platerecognizer_telecamera_cancello_profile_000
mode: single
```
