### ISSUE TITLE
No "image_processing" on States (HA)

### ISSUE THREAD

**Issue by Allread** [robmarkcole/HASS-plate-recognizer#85]
hello :) 
I follow this tuto for PR via HACS
- I have "/config/custom_components/platerecognizer"
- I have "/config/www/plate" for folder
- I have write in configuration.yaml

```
image_processing:
  - platform: platerecognizer
    api_token: xxxxxxxxxxxxxx
    regions:
      - fr
    watched_plates:
      - xxxxxxx
      - xxxxx
    save_file_folder: /config/www/plate/
    save_timestamped_file: True
    always_save_latest_file: True
    mmc: True
    detection_rule: strict
    region: strict
    source:
      - entity_id: camera.camera_portail_mainstreamprofile
```

But I don't have "image processing" in Dev Tools State"

![image](https://github.com/robmarkcole/HASS-plate-recognizer/assets/16807391/af7b9b10-9586-4cbf-85c6-9b5892bd4436)

Any help ?
